TodaysBlogs/TodaysBlogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('blog/', include("blog.urls"))
]

TodaysBlogs/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_page, name="blog_page"),
    path("add/", views.add_blog, name="add_new_blog"),
    path("view/", views.view_blogs, name="view_blogs_page"),
    path("details/<blog_id>/", views.blog_detail, name="blog_detail"),
    path("update/<blog_id>/", views.update_blog, name="update_blog"),
    path("delete/<blog_id>/", views.delete_blog, name="delete_blog"),
    path("search/", views.search_blog, name="search_blog"),
    path("comment/add/<blog_id>/", views.add_comment, name="add_comment"),
]

TodaysBlogs/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.main_page, name="main_page"),
    path("theme/dark/", views.themeSetDark, name="theme_set_dark"),
    path("theme/light/", views.themeSetLight, name="theme_set_light"),
    
]

TodaysBlogs/blog/models.py
from django.db import models

class Blog(models.Model):

    title = models.CharField(max_length=1024)
    content = models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateField()

class Comment(models.Model):

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=512)
    content = models.TextField()

TodaysBlogs/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Blog, Comment



# Create your views here.

def blog_page(request : HttpRequest):
    
    return render(request, 'blog/index.html')


def add_blog(request : HttpRequest):

    if request.method == "POST":
        #to add a new entry
        new_blog = Blog(title= request.POST["title"], content = request.POST["content"], is_published = request.POST["is_published"], publish_date=request.POST["publish_date"])
        new_blog.save()
        return redirect("blog:view_blogs_page")


    return render(request, "blog/add_blog.html")


def view_blogs(request : HttpRequest):

    view_blogs = Blog.objects.all()

    context = {"view_blogs" : view_blogs}
    return render(request, "blog/index.html", context)


def update_blog(request : HttpRequest, blog_id):

    blog = Blog.objects.get(id=blog_id)
    blog.publish_date = blog.publish_date.isoformat #to make it compatible with input value in html
    if request.method == "POST":
        blog.title = request.POST["title"]
        blog.content = request.POST["content"]
        blog.is_published = request.POST["is_published"]
        blog.publish_date = request.POST["publish_date"]

        blog.save()
        return redirect("blog:view_blogs_page")

    return render(request, "blog/update_blog.html", {"blog" : blog})

def delete_blog(request : HttpRequest, blog_id):
    blog = Blog.objects.get(id=blog_id)
    blog.delete()
    return redirect("blog:view_blogs_page")

def blog_detail(request : HttpRequest, blog_id):

    blog = Blog.objects.get(id=blog_id)
    comment = Comment.objects.filter(blog=blog)
    commentIndex = Comment.objects.filter(blog=blog).count()

    return render(request, "blog/blog_detail.html", {"blog" : blog, "comment" : comment, "commetIndex":commentIndex})

def search_blog(request : HttpRequest):
    if request.method == "POST":
        search = request.POST['search']
        search_blog = Blog.objects.filter(title__contains=search)

        return render(request, "blog/search_blog.html", {'search_blog':search_blog}) 
    else:
        return render(request, "blog/search_blog.html", {})

def add_comment(request : HttpRequest, blog_id):

    if request.method == "POST":
        blog = Blog.objects.get(id=blog_id)
        new_comment = Comment(blog=blog, name=request.POST["name"], content = request.POST["content"])
        new_comment.save()

    return redirect("blog:blog_detail", blog_id=blog_id)

TodaysBlogs/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse


# Create your views here.

def main_page(request : HttpRequest):
    
    return render(request, 'main/index.html')

def themeSetDark(request : HttpRequest):
    response = redirect("main:main_page")
    response.set_cookie("theme","Dark", max_age=60*60*24*7)
    return response

def themeSetLight(request : HttpRequest):
    response = redirect("main:main_page")
    response.set_cookie("theme","Light", max_age=60*60*24*7)

    return response

TodaysBlogs/blog/templates/blog/add_blog.html
{% extends 'main/base.html' %}

{% block title %} Add a New Blog {% endblock %}

{% block content %}

<div class="container">
<h2>Add a New Blog</h2>

<form action="" method="POST">
    {% csrf_token %}
        <div class="transbox">
        <div class="row">
            <div class="col" id = "box">
                <input type="text" name="title" class="form-control m-2 text-dark" placeholder="Title"/>

                <textarea class="form-control m-2 text-dark" name="content" placeholder="Content"></textarea>

                <select name="is_published" class="form-select m-2 text-dark" aria-label="Default select example">
                    <option selected >Is it published?</option>
                    <option value="True">Yes</option>
                    <option value="False">No</option>
                </select>
            
            <input type="date" name="publish_date" placeholder="Publish date" class= "m-2"/>

            <br/>
            <input type="submit" class="btn btn-dark m-2" value="New Blog" />
        </div>
    </div>
  </div>
    
</form>

</div>



{% endblock %}

TodaysBlogs/blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}

{% block title %} Details for {{ blog.title }}  {% endblock %}


{% block content %}

<div class="container">

    <div class="m-3 d-flex gap-2">
        <h1>{{ blog.title }}</h1>
        <div class="transbox m-2">
        <a href="{% url 'blog:update_blog' blog.id %}" class="btn btn-primary">Update</a>
        <a href="{% url 'blog:delete_blog' blog.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    <h6>
        {% if blog.is_pubilshed %} 
            Pubilshed
        {% else %}
            Not Pubilshed
        {% endif %}
    </h6>
    
    <p>Content: {{ blog.content }}</p>
    <p class="card-text">Published: {{ blog.publish_date }}</p>

</div>
</br>

    <div class="container">
        <div class="transbox">
        <form action="{% url  'blog:add_comment' blog.id %}" method="post">
            {% csrf_token %}
            <input type="text" name="name" class="form-control mt-2 text-dark" placeholder="User Name..." /> 
            <textarea name="content" class="form-control mt-2 text-dark" placeholder="Comment..."></textarea>
            <input class="btn btn-secondary mt-2" type="submit" value="Add Comment" />
        </form>
        </div>
        
    </div>


    <div  class="container">
    <h3>Comments :</h3>
    {% if commetIndex == 0 %}
    <div class="card transbox">
        <div class="card-body">
          There is no comments
        </div>
      </div>
    {% else %}
    <div class="card transbox"> 
        <div class="card-body">
        {% for comment in comment  %}
            <div class="p-2 mt-2">

            <h5>{{ comment.name }}</h5>
            <p>{{ comment.content }}</p>

        </div>
        {% endfor %}
        </div>
    </div>
    {% endif %}
        
        
        
    </div>










{% endblock %}

TodaysBlogs/blog/templates/blog/index.html
{% extends 'main/base.html' %}

{% block title %} Latest Blogs {% endblock %}

{% block content %}
<div class="container">
    <h2> Latest Blogs !</h2>

    <div class="row">
        {% for blog in view_blogs %}
            <div class="col-3">
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <a href="{% url 'blog:blog_detail' blog.id %}"><h5 class="card-title">{{ blog.title }}</h5></a>
                  <h6 class="card-subtitle mb-2 text-muted">
                    {% if blog.is_pubilshed %} 
                      Pubilshed
                    {% else %}
                      Not Pubilshed
                    {% endif %}
                  </h6>
                  <p class="card-text">Content: {{ blog.content }}</p>
                  <p class="card-text">Published: {{ blog.publish_date }}</p>
                </div>
              </div>
            </div>
        {% endfor %}


    </div>
</div>
{% endblock %}

TodaysBlogs/blog/templates/blog/search_blog.html
{% extends 'main/base.html' %}

{% block title %} Update Blog {% endblock %}

{% block content %}
<div class="container">
    <h2> Search Result !</h2>

    <div class="row">
        {% for blog in search_blog %}
        <div class="col-3">
            <div class="card" style="width: 18rem;">
            <div class="card-body">
                <a href="{% url 'blog:blog_detail' blog.id %}"><h5 class="card-title">{{ blog.title }}</h5></a>
                <h6 class="card-subtitle mb-2 text-muted">
                {% if blog.is_pubilshed %} 
                    Pubilshed
                {% else %}
                    Not Pubilshed
                {% endif %}
                </h6>
                <p class="card-text">Content: {{ blog.content }}</p>
                <p class="card-text">Published: {{ blog.publish_date }}</p>
            </div>
            </div>
        </div>
        {% endfor %}


{% endblock %}

TodaysBlogs/blog/templates/blog/update_blog.html
{% extends 'main/base.html' %}

{% block title %} Update Blog {% endblock %}

{% block content %}

<div class="container">
<h2>Updating Blog</h2>

<form action="" method="POST">
    {% csrf_token %}
        <div class="transbox">
        <div class="row">
            <div class="col" id = "box">
                <input type="text" name="title" class="form-control m-2 text-dark" placeholder="Title" value="{{ blog.title }}"/>

                <textarea class="form-control m-2 text-dark" name="content" placeholder="Content">{{ blog.content }}</textarea>

                <select name="is_published" value="{{blog.is_published}}" class="form-select m-2 text-dark" aria-label="Default select example">
                    <option selected >Is it published?</option>
                    <option value="True" {% if blog.is_published == True %} selected {% endif %}>Yes</option>
                    <option value="False" {% if blog.is_published == False %} selected {% endif %}>No</option>
                </select>
            
            <input type="date" name="publish_date" value="{{ blog.publish_date }}" placeholder="Publish date" class= "m-2"/>

            <br/>
            <input type="submit" class="btn btn-dark m-2" value="Update Blog" />
        </div>
    </div>
  </div>
    
</form>

</div>



{% endblock %}

TodaysBlogs/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Today's Blog {% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>       
        div.transbox {
          border: black;
          opacity: 0.7;
        }
        </style>
</head>
{% load static %}
{% if request.COOKIES.theme == "Dark" %}
<body data-bs-theme="dark">
    <div style="background-image: url({% static 'images/indexDark.jpg' %}); background-repeat: no-repeat; background-size: cover; background-position: center center; min-height: 100vh;">

{% else  %}
<body data-bs-theme="white">
    <div style="background-image: url({% static 'images/indexLight.jpg' %}); background-repeat: no-repeat; background-size: cover; background-position: center center; min-height: 100vh;">


{% endif %} 
<div style="background-image: url({% static 'images/index.jpg' %}); background-repeat: no-repeat; background-size: cover; background-position: center center; min-height: 100vh;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary ">
        <div class="container-fluid">
            <a class="navbar-brand" href="http://127.0.0.1:8000/">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <a class="nav-link dropdown-toggle" href="city/" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Blogs
                        </a>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="http://127.0.0.1:8000/blog/view">View blogs</a>
                        <li><a class="dropdown-item" href="http://127.0.0.1:8000/blog/add/">Add a new Blog</a>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex m-2" action="{% url 'blog:search_blog' %}" method="POST">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form> 
                <form class="d-flex" role="search">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Theme
                        </button>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'main:theme_set_light' %}">Light</a></li>
                          <li><a class="dropdown-item" href="{% url 'main:theme_set_dark' %}">Dark</a></li>
                        </ul>
                    </div>
                </form>
                
            </div>
        </div>
    </nav>
    {% block content %}
        
    {% endblock %}
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

TodaysBlogs/main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %} Today's Blog {% endblock %}

{% block content %}

<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 text-center m-5 text-dark">
      <h1 class="font-weight-bold mt-sm-5">Welcome to Today's Blog</h1>
      <hr class="hr-light">
      <h5 class="mb-4">Here you can see and add blog and share it with the world
      </h5>
    </div>
    <div class="accordion accordion-flush" id="accordionFlushExample">
                      
    </div>
  </div>
</div>
{% endblock %}