Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

Blog/subjects/urls.py
from django.urls import path
from . import views

app_name = 'subjects'

urlpatterns = [
    
    path('',views.home_page , name="home_page"),
    path('read/',views.read_page,name="read_page"),
    path('write/',views.write_page,name="write_page"),
    path('about/',views.about_page,name="about_page"),
    path('details/<subject_id>/',views.details_page,name="details_page"),
    path('updated/<subject_id>/',views.update_page,name="update_page"),
    path('delete/<subject_id>/',views.delete_page,name="delete_page"),
    path('search/',views.search_page,name="search_page"),
    path('review/<subject_id>/',views.review,name="review"),



]

Blog/subjects/models.py
from django.db import models

class Subject(models.Model):

    title = models.CharField(max_length=256)
    content = models.TextField()
    is_published = models.BooleanField(default=True)
    published_date = models.DateTimeField(auto_now_add=True)


class Review(models.Model):

    subject = models.ForeignKey(Subject, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=255)
    content = models.TextField()
    

Blog/subjects/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse, HttpRequest
from .models import Review, Subject


def home_page(request : HttpRequest):
    return render(request,"subjects/home_page.html")


def write_page(request : HttpRequest):

    if request.method == "POST":
        new_subject = Subject(title= request.POST["title"], content = request.POST["content"], is_published = request.POST["is_published"], published_date=request.POST["published_date"])
        new_subject.save()
        return redirect("subjects:read_page")

    return render(request,"subjects/write.html")
    

def read_page(request :HttpRequest):
    
    subjects_save = Subject.objects.all()
    context = {"subjects_save" : subjects_save}
    return render(request,"subjects/read.html", context)
    


def details_page(request : HttpRequest,subject_id):
    subject = Subject.objects.get(id=subject_id)
    reviews = Review.objects.filter(subject=subject)

    return render(request,"subjects/subject_details.html", {"subject" : subject, "review": reviews})



def update_page(request : HttpRequest,subject_id):

    subject = Subject.objects.get(id=subject_id)
    
    if request.method == "POST":

        subject.title = request.POST["title"]
        subject.content = request.POST["content"]
        subject.is_published = request.POST["is_published"]
        
        subject.save()
        return redirect("subjects:read_page")

    return render(request,"subjects/update_subject.html", {"subject" : subject})

def delete_page(request : HttpRequest, subject_id):
    subject = Subject.objects.get(id=subject_id)
    subject.delete()
    return redirect("subjects:read_page")
    
def search_page(request : HttpRequest):
    
    if request.method == 'GET':
        search = request.GET.get("search")
        result_search = Subject.objects.filter(title__icontains=search)  

        return render(request,"subjects/result_search.html", {"result_search" : result_search})


def review(request : HttpRequest, subject_id):

    if request.method == "POST":
        subject = Subject.objects.get(id=subject_id)
        new_review = Review(subject=subject, name=request.POST["name"], content = request.POST["content"])
        new_review.save()

    return redirect("subjects:details_page", subject_id=subject_id)

    

def about_page(request : HttpRequest):
    return render(request,"subjects/about.html")

Blog/subjects/templates/subjects/about.html
{% extends 'subjects/base.html' %}
{% block title %}ABOUT{% endblock %}


{%block content%}
<div class="container ">
    <h3 class="text-center text-primary mt-5">
        In Our Blog We Write About Programming Language
        <br/>
        If You Want Help Us To Share Knowledge
        <br/> <br/>
         Contact us <a href="mailto:Blog@Programming.com"> Email </a>
    </h3>
</div>
{% endblock %}

Blog/subjects/templates/subjects/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;700&display=swap');
        *{
            font-family: 'M PLUS Rounded 1c', sans-serif !important;
         }
    </style>
    
    <title>{% block title %}HOME PAGE{% endblock %}</title>
</head>
<body>

    <nav class="bg-body-tertiary " >
        <div class="container-fluid d-inline-block">
          <ul class="nav justify-content-center">
            
            <li class="nav-item">
              <h4><a class="nav-link me-2 mt-1 fw-bold active" aria-current="page" href="/">BLOG</a></h4>
            </li>
            <li class="nav-item">
              <a class="nav-link me-2 mt-2 fw-light" href="{% url 'subjects:read_page' %}">READ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link me-2 mt-2 fw-light" href="{% url 'subjects:write_page' %}">WRITE</a>
            </li>
            <li class="nav-item">
              <a class="nav-link me-2 mt-2 fw-light" href="{% url 'subjects:about_page' %}">ABOUT</a>
            </li>
            <li class="nav-item md-5">
              <form action="{% url 'subjects:search_page' %}" method="GET" class="d-flex mt-2 me-2" role="search">
                <input name="search" class="form-control me-2" type="search" placeholder="Search" > 
              </form>
            </li>
          </ul>
              
            </div>
          </div>
      </nav>  
      
    
    {% block content %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

Blog/subjects/templates/subjects/home_page.html
{% extends 'subjects/base.html' %}
{% block title %}HOME{% endblock %}


{%block content%}
<div class="container ">
    <h3 class="text-center text-primary mt-5">
        Welcome to Our Blog We Share Knowledge About Programming Language
        <br/> Use Navbar to Transfers between pages :)
    </h3>
</div>
{% endblock %}

Blog/subjects/templates/subjects/read.html
{% extends 'subjects/base.html' %}
{% block title %}READ{% endblock %}


{%block content%}
<div class="container row-5 mt-5">
    
<div class="row mb-2">
    {% for subject in subjects_save %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <h3 class="mb-2"><strong>{{subject.title}}</strong></h3>
                <div class="mb-1 text-muted me-3 mb-3">{{subject.published_date}} <br/> Is Published : {{subject.is_published}}</div>
                <p class="card-text mb-auto">{{subject.content}}</p>
                <a href="{% url 'subjects:details_page' subject.id %}" class="stretched-link mt-3">Click to read more</a>
                </div>
                
            </div>
        </div> 
    {% endfor %}
</div>

</div>

{% endblock %}

Blog/subjects/templates/subjects/result_search.html
{% extends 'subjects/base.html' %}
{% block title %}Search Result{% endblock %}


{%block content%}
<div class="container ">
   
    <div class="text-center text-primary mt-5 mb-5">
        {% for result in result_search %}
           <div class="text-center mb-3">
                <h1><strong>{{result.title}}</strong></h1>
                <h6>{{result.published_date}}</h6>
           </div>
           <h3>{{result.content}}</h3>
        {% endfor %}
    </div>
   
</div>
{% endblock %}

Blog/subjects/templates/subjects/subject_details.html
{% extends 'subjects/base.html' %}

{% block title %} Details Subject | {{ subject.title }}  {% endblock %}


{% block content %}

<div class="container mt-5">
    <div class="text-center ms-5 me-5 ps-5 pe-5">
        <h1 class="mb-3">{{ subject.title }}</h1>
        <div class="mt-3 mb-3">
            <a href="{% url 'subjects:update_page' subject.id %}">to Edit Subject</a>
            <br/>
            <a class="mt-3" href="{% url 'subjects:delete_page' subject.id %}" >to Delete Subject</a>
        </div>
        <h6 class="mb-5">Published Date on: {{ subject.published_date}}</h6>
        <h4>{{ subject.content }}</h4>
    </div>


    <div><h3 class="mt-5">Add Review</h3>
        <div>
            <form action="{% url 'subjects:review' subject.id %}" method="POST">
                {% csrf_token %}

                <input type="text" name="name" class="form-control mt-3" placeholder="Enter Your Name" /> 

                <textarea name="content" class="form-control mt-3 " placeholder="Your Review here"></textarea>

                <input class="btn btn-primary mt-3" type="submit" value="Add Review" />

            </form>
        </div>
    </div>


    <div  class="m-5">
        <h3>All Reviews :</h3>
        {% for review1 in review  %}
            <div class="p-3 mb-4 ms-5 me-5 bg-info bg-opacity-10 border rounded-pill rounded-5">
                <div class="ps-5">
                    <h5 class="mb-2"><strong>Name : </strong>{{ review1.name }}</h5>
                    <p> <strong>The Review : </strong><br/>{{ review1.content }}</p>
                </div>

            </div>
            {% endfor %}
    </div>

    

</div>

{% endblock %}

Blog/subjects/templates/subjects/update_subject.html
{% extends 'subjects/base.html' %}
{% block title %}Edit Subject | {{ subject.title }}{% endblock %}


{%block content%}
<div class="container ">
    <form  action="" method="POST">
        {% csrf_token %}
        <div class="position-absolute top-50 start-50 translate-middle " style="width: 720px;">  
            <label class="form-label">Title</label>
            <input value="{{subject.title}}" class="form-control mb-4" type="text" name="title" />
                
            <label class="form-label">Content</label>
            <textarea class="form-control mb-4" name="content">{{ subject.content }}</textarea>
            
            <fieldset class="row mb-3" >
                <legend class="col-form-label col-sm-2 pt-0" >Is Published</legend>
                <div class="col-sm-10 ">

                    <input value="{{subject.is_published}}"{% if subject.is_published == 'True' %} selected {% endif %} class="form-check-input"  type="radio" name="is_published" id="True" value="True" checked>
                    <label class="form-check-label" for="true">True</label>
                    
                    <input value="{{subject.is_published}}"{% if subject.is_published == 'False' %} selected {% endif %} class="form-check-input ms-5" type="radio" name="is_published" id="False" value="False">
                    <label class="form-check-label" for="false">False</label>
                    
                </div>
            </fieldset>
            
            
            <label class="form-label">Publish Date</label>
            <input class="mb-4" type="date" name="published_date"  />
            
            <div class="d-grid gap-2 col-6 mx-auto ">
                <input class="btn btn-primary me-5 ms-5" type="submit" value="Save Subject" />
            </div>

        </div>

    </form>
</div>
{% endblock %}

Blog/subjects/templates/subjects/write.html
{% extends 'subjects/base.html' %}
{% block title %}WRITE{% endblock %}


{%block content%}
<div class="container ">
    <form  action="" method="POST">
        {% csrf_token %}
        <div class="position-absolute top-50 start-50 translate-middle " style="width: 720px;">  
            <label class="form-label">Title</label>
            <input class="form-control mb-4" type="text" name="title" />
                
            <label class="form-label">Content</label>
            <textarea class="form-control mb-4" name="content"></textarea>
            
            <fieldset class="row mb-3">
                <legend class="col-form-label col-sm-2 pt-0">Is Published</legend>
                <div class="col-sm-10 ">

                    <input class="form-check-input" type="radio" name="is_published" id="True" value="True" checked>
                    <label class="form-check-label" for="true">True</label>
                    
                    <input class="form-check-input ms-5" type="radio" name="is_published" id="False" value="False">
                    <label class="form-check-label" for="false">False</label>
                    
                </div>
            </fieldset>
            
            
            <label class="form-label">Publish Date</label>
            <input class="mb-4" type="date" name="published_date"  />
            
            <div class="d-grid gap-2 col-6 mx-auto ">
                <input class="btn btn-primary me-5 ms-5" type="submit" value="Save Subject" />
            </div>

        </div>

    </form>
</div>
{% endblock %}