Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

Blog/blog_app/urls.py
from django.urls import path
from . import views





app_name = "blog"

urlpatterns = [
    path("", views.index, name="blogs_page" ),
    path("blogs/add/", views.add_post, name="add_new_post"),
    path("blogs/details/<post_id>", views.detail_post, name="details_post"),
    path("blogs/update/<post_id>", views.post_update, name="post_update"),
    path("blogs/delete/<post_id>", views.delete_post, name="post_delete"),
    path("blogs/search/", views.search, name="search_post"),
    path("blogs/commit/<post_id>", views.add_comment, name="add_comment"),

]

Blog/blog_app/models.py
from django.db import models

# Create your models here.


class Posts(models.Model):

    title = models.CharField(max_length=1024)
    content =  models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateField()


class Comment(models.Model):

    post_name = models.ForeignKey(Posts, on_delete=models.CASCADE)
    name = models.CharField(max_length=102)
    content =  models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

Blog/blog_app/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest ,HttpResponse
from .models import Posts , Comment

# Create your views here.




def index(request : HttpRequest):

    blogs = Posts.objects.all()
    context = {
        "blog" : blogs
    }
    return render(request ,"blogs/index.html" , context)




def add_post(request : HttpRequest):

    if request.method == "POST":
        #to add a new entry
        new_post = Posts(
            
            title = request.POST["title"],
            content = request.POST["content"],
            is_published = request.POST['is_published'],
            publish_date = request.POST["publish_date"]
        ).save()
        return redirect("blog:blogs_page")
    return render(request, "blogs/Add_post.html")




def detail_post(request : HttpRequest , post_id ):
    
    details = Posts.objects.get(id = post_id)
    result = Comment.objects.filter(post_name=details)

    return render(request , "blogs/post_details.html" , {"details" : details, "result" : result})


def post_update(request : HttpRequest , post_id ):

    post = Posts.objects.get(id = post_id)

    if request.method == "POST":
       
            
            post.title = request.POST["title"]
            post.content = request.POST["content"]
            post.is_published = request.POST["is_published"]
            post.publish_date = request.POST["publish_date"]

            post.save()
            return redirect("blog:blogs_page")
    return render(request , "blogs/post_update.html" ,  {"post" : post})


def delete_post(request : HttpRequest, post_id):
    post = Posts.objects.get(id=post_id)
    post.delete()
    return redirect("blog:blogs_page")



def search(request : HttpRequest):

    if request.method == "GET": 

            post_name =  request.GET.get('search')      
            search_post = Posts.objects.filter(title__contains = post_name)
               
            return render(request , "blogs/search.html" , {"search_post" : search_post})





def add_comment(request : HttpRequest, post_id):

    if request.method == "POST":
        post = Posts.objects.get(id=post_id)
        new_comment = Comment(post_name=post, name=request.POST["name"], content = request.POST["content"])
        new_comment.save()

    return redirect("blog:details_post", post_id=post_id)

Blog/blog_app/templates/blogs/Add_post.html
{% extends 'blogs/base.html' %}

 {% block title %} Add a New Post {% endblock %}


{% block content %}




<div class="container">

  <form action="" method="POST" class="form-inline">
        {% csrf_token %}


    <label class="form-label"><h5>Title </h5></label>
    <input type="text" name="title" class="form-control" />

    <label class="form-label"><h5>Content</h5></label>
    <textarea class="form-control" name="content"></textarea>
    <br>

    <div class="flex-md-row">

        <div class="col">
            <label class="form-label"><h5>Date</h5></label>
            <input type="date" name="publish_date" />
        </div>

        <label>Is Published</label>
        <select name="is_published" class="form-control">
            <option value="True">Yes</option>
            <option value="False">No</option>
        </select>
        
    </div>
<br>

    <div class="">
        <input type="submit" class="btn btn-primary" value="New Post" />
        <a class="btn btn-secondary" href="{% url 'blog:blogs_page' %}" role="button">Back</a>
    </div>
  </form>

  
</div>

{% endblock %}

Blog/blog_app/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Hugo 0.72.0" />
    <title>Blog</title>
    <link
      rel="canonical"
      href="https://v5.getbootstrap.com/docs/5.0/examples/blog/"
    />

    <link rel="stylesheet" href="/Blog/blog_app/static/style.css" />
    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
      integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I"
      crossorigin="anonymous"
    />
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
      integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    
    <div class="container">
      

      <header class="blog-header py-3">
        
      </header>
      

      <div class="p-4 p-md-5 mb-4 text-white rounded" style="background-color: rgb(12, 92, 173)">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">BLOG POSTS</h1>

          <p class="lead my-3">Many interesting articles</p>
          
        
          
          
        </div>
        
      </div>
    </div>
    

    {% block content %} {% endblock %}
  </body>
</html>

Blog/blog_app/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block title %} Post {% endblock %}


{% block content %}


<div class="container">
    <header class="blog-header py-3">
        


        <form action="{% url 'blog:search_post' %}" method="get">
            <input type="text" name="search" placeholder="Search by title" value="{{request.GET.title}}">
            <input type="submit" value="Search">
        </form>
        
           
        
        <p class="lead mb-0">
            <a href="{% url 'blog:add_new_post' %}" class="text-blue font-weight-bold" >Add New Post</a>
          </p>
    </header>

     
    <div class="row mb-2">
        
        {% for post in blog  %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <!-- <strong class="d-inline-block mb-2 text-primary"></strong> -->
                    <a href="{% url 'blog:details_post' post.id %}"><h4> {{ post.title }} </h4></a>
                    <hr>
                    <div class="mb-2 text-blue"><b>{{post.publish_date}}</b></div>
                    <p class="card-text mb-auto">{{post.content}}</p>
                    <a href="{% url 'blog:details_post' post.id %}" class="stretched-link">Continue reading</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>       
</div>


{% endblock %}  


<div class="row mb-2">
  

    

Blog/blog_app/templates/blogs/post_details.html
{% extends 'blogs/base.html' %}

{% block title %} Details {% endblock title %}

 {% block content   %}
 
 <div class="container">
    
   <h1>{{ details.title }}</h1>
  <h6> {{ details.publish_date}} </h6>
  <hr>
  <p><h5>{{details.content}}</h5> </p>

  <hr>
  <div class="d-flex "><a href="{% url 'blog:post_update' details.id %}" class="btn btn-primary">update</a> &nbsp; <a href="{% url 'blog:post_delete' details.id %}" class="btn btn-danger">delete</a>
    &nbsp; <a class="btn btn-secondary" href="{% url 'blog:blogs_page' %}" role="button">Back</a>
  </div>
<hr>

<div  class="m-3">
        <h3>Comment :</h3>
        {% for p in result  %}
            <div class="p-2 border mt-2">

                <h5>{{ p.name }}</h5>
                <p>{{ p.content }}</p>

            </div>
        {% endfor %}
        <div class="mt-3">
          <form action="{% url  'blog:add_comment' details.id %}" method="post">
              {% csrf_token %}

              <input type="text" name="name" class="form-control" placeholder="Your Name.." /> 

              <textarea name="content" class="form-control" placeholder="Your Comment here..."></textarea>

              <input class="btn btn-primary mt-2" type="submit" value="Add Comment" />

          </form>
      </div>
    </div>

    
        


 </div>
 {% endblock %}

 

Blog/blog_app/templates/blogs/post_update.html
{% extends 'blogs/base.html' %}

 {% block title %} Add a New Post {% endblock %}


{% block content %}




<div class="container">

  <form action="" method="POST" class="form-inline">
        {% csrf_token %}


    <label class="form-label"><h5>Title </h5></label>
    <input type="text" name="title" class="form-control"  value="{{ post.title }}"/>

    <label class="form-label"><h5>Content</h5></label>
    <textarea class="form-control" name="content"> {{ post.content  }} </textarea>
    <br>

    <div class="flex-md-row">

        <div class="col">
            <label class="form-label"><h5>Date</h5></label>
            <input type="date" name="publish_date" value="post.publish_date" />
        </div>

        
        <select  name="is_published" class="form-select">
            <option  value="True" {% if post.is_published == True %} selected {% endif %}>Yes</option>
            <option  value="False" {% if post.is_published == False %} selected {% endif %}>No</option>
        </select>
        
    </div>
    <br>

    <div class="">
        <input type="submit" class="btn btn-primary" value="Update" />
        <a class="btn btn-secondary" href="{% url 'blog:blogs_page' %}" role="button">Back</a>
    </div>
  </form>

  
</div>

{% endblock %}

Blog/blog_app/templates/blogs/search.html
{% extends 'blogs/base.html' %}

{% block title %} Details {% endblock title %}

 {% block content   %}
 
 <!-- {% for post in search_post %}
 <div class="container">
    <div class="col-3">
        <div class="p-4 shadow" >
            <a href="{% url 'blog:details_post' post.id %}"><h4>{{ post.title }}</h4></a>
            <h6>Date: {{ post.publish_date }}</h6>
            
        </div>
    </div>
 </div> -->


    {% for post in search_post %} 
       <div class="container">

        <a href="{% url 'blog:details_post' post.id %}"><h4> {{ post.title }} </h4></a>
            <h6> {{ post.publish_date}} </h6>
            <hr>
            <p><h5>{{post.content}}</h5> </p>

            
            
            {% endfor %}
        
            {% endfor %}
            <a class="btn btn-secondary" href="{% url 'blog:blogs_page' %}" role="button">Back</a>
        </div>
{% endblock %}

 