BlogWepsite/BlogWepsite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('main.urls')),

]

BlogWepsite/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index_page"),
    path("posts/add/", views.post_detail, name="post_detail"),
    path("update/<blog_id>/", views.update_blog, name="update_blog"),
    path("delete/<blog_id>/", views.delete_blog, name="delete_blog"),
    path("latest/", views.latest_blog, name="latest_blog_page" ),
    path("details/<blog_id>/", views.blog_detail, name="blog_detail"),
    path("search/", views.search_blog, name="search_blog"),
     path("review/add/<blog_id>/", views.add_review, name="add_review"),

]

BlogWepsite/main/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=1024)
    content = models.TextField()
    is_published = models.BooleanField()
    publish_date = models.DateTimeField(auto_now_add=True)


class Review(models.Model):

    blog = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=512)
    content = models.TextField()
    rating =  models.FloatField()

    created_at = models.DateTimeField(auto_now_add=True)

BlogWepsite/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Post , Review


# Create your views here.

def index(request : HttpRequest):
    
    return render(request, 'main/index.html')


def post_detail(request : HttpRequest):

    if request.method == "POST":
        new_blog = Post(title= request.POST["title"], content = request.POST["content"], is_published = request.POST["is_published"], publish_date=request.POST["publish_date"])
        new_blog.save()
        return redirect("main:latest_blog_page")


    return render(request, "main/post_detail.html")



def latest_blog(request : HttpRequest):

    display = int(request.GET.get("display", 10))

    latest_blog = Post.objects.all()

    context = {"latest_blog" : latest_blog}
    return render(request, "main/index.html", context)



def update_blog(request : HttpRequest, blog_id):

    blog = Post.objects.get(id=blog_id)
    blog.publish_date = blog.publish_date.isoformat 
    if request.method == "POST":
        blog.title = request.POST["title"]
        blog.content = request.POST["content"]
        blog.is_published = request.POST["is_published"]
        blog.publish_date = request.POST["publish_date"]

        blog.save()
        return redirect("main:latest_blog_page")

    return render(request, "main/update.html", {"main" : blog})


def blog_detail(request : HttpRequest, blog_id):

    blog = Post.objects.get(id=blog_id)
    reviews = Review.objects.filter(Post=blog)
    context =  {
        "Post" : blog, 
        "reviews" : reviews
        }


    return render(request, "main/detail.html", context)
# 

def delete_blog(request : HttpRequest, blog_id):
    blog = Post.objects.get(id=blog_id)
    blog.delete()
    return redirect("main:latest_blog_page")




def search_blog(request : HttpRequest):
    if request.method == "POST":
        search = request.POST['search']
        search_blog = Post.objects.filter(title__contains=search)

        return render(request, "main/search.html", {'search_blog':search_blog }) 
    else:
        return render(request, "main/search.html", {})



def add_review(request : HttpRequest, blog_id):

    if request.method == "POST":
        blog = Post.objects.get(id=blog_id)
        new_review = Review(blog=blog, name=request.POST["name"], content = request.POST["content"], rating = request.POST["rating"])
        new_review.save()

    return redirect("main:blog_detail", blog_id=blog_id)

BlogWepsite/main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} General Blog {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Blogger</span>
            </a>

            <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'main:post_detail' %}" class="nav-link active" aria-current="page">Add Post</a></li>
            <li class="nav-item"><a href="{% url 'main:search_blog' %}" class="nav-link " aria-current="page">search</a></li>

            <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link">About</a></li>
            </ul>
        </header>
        </div>

        <p class = "container fw-lighter" style="text-align: center;width:800px;height:400px; padding: 20px;">Welcome To Our Blog Page , You Can Start Blogging .</p>
      

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

BlogWepsite/main/templates/main/detail.html
{% extends 'main/base.html' %}

{% block title %} Details for {{ blog.title }}  {% endblock %}


{% block content %}

<div class="container">

    <div class="m-3 d-flex gap-2">
        <h1>{{ blog.title }}</h1>
        <div class="transbox m-2">
        <a href="{% url 'main:update_blog' blog.id %}" class="btn btn-primary">Update</a>
        <a href="{% url 'main:delete_blog' blog.id %}" class="btn btn-danger">Delete</a>
        <p>{{ blog.content }}</p>
        </div>

        <hr/>

        <div  class="container">
            <h3>Reviews :</h3>
            {% for review in reviews  %}
                <div class="p-2 border mt-2">
        
                    <h5>{{ review.name }}</h5>
                    <h6>{{ review.rating }} Stars</h6>
                    <p>{{ review.content }}</p>
        
                </div>
            {% endfor %}
            </div>
        
        
            <div class="container-md">
                <h3>Add Review</h3>
                <div class="contaner" >
                    <form action="{% url  'main:add_review' blog.id %}" method="post">
                        {% csrf_token %}
        
                        <input type="text" name="name" class="form-control" placeholder="Your Name.." /> 
        
                        <textarea name="content" class="form-control" placeholder="Your Review here..."></textarea>
        
                        <div class="mt-3">
                            <h4>Choose the Rating:</h4>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="rating" value="1" id="flexRadioDefault1">
                            <label class="form-check-label" for="flexRadioDefault1">
                            1 Star
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="rating" value="2" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                            2 Star
                            </label>
                        </div>
        
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="rating" value="3" id="flexRadioDefault2" checked>
                            <label class="form-check-label" for="flexRadioDefault2">
                            3 Star
                            </label>
                        </div>
                        </div>
                        
        
                        <input class="btn btn-primary "   type="submit" value="Add Review" />
        
                    </form>
                </div>
            </div>
        
        
        {% endblock %}




    

BlogWepsite/main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}
<div class="container">
    <h2 style="text-align: center;"> Latest Blogs !</h2>

    <div class="row">
        {% for Post in latest_blog %}
            <div class="col-3">
              <div class="card" style="width: 45rem;">
                <div class="card-body">
                  <a href= "{% url 'main:blog_detail' blog.id %}"><h5 class="card-title">{{ blog.title }}</h5></a>
                  <h6 class="card-subtitle mb-2 text-muted">
                    {% if blog.is_pubilshed %} 
                      Pubilshed
                    {% else %}
                      Not Pubilshed
                    {% endif %}
                  </h6>
                  <p class="card-text">Content: {{ blog.content }}</p>
                  <p class="card-text">Published: {{ blog.publish_date }}</p>
                </div>
              </div>
            </div>
        {% endfor %}


    </div>
</div>
{% endblock %}

BlogWepsite/main/templates/main/post_detail.html
{% extends 'main/base.html' %}

{% block title %} Add a New Blog {% endblock %}

{% block content %}

<div class="container">
<h2 style="text-align: center;">Add a New Blog !</h2>

<form action="" method="POST">
        <div class="transbox">
        <div class="row">
            <div class="col" id = "box">
                <input type="text" name="title" class="form-control m-2 text-dark" placeholder="Title"/>

                <textarea class="form-control m-2" name="content" placeholder="Content"></textarea>

                <select name="is_published" class="form-select m-2" aria-label="Default select example">
                    <option selected >Is it published?</option>
                    <option value="True">Yes</option>
                    <option value="False">No</option>
                </select>
            
            <input type="date" name="publish_date" placeholder="Publish date" class= "m-2"/>
            <br/>
            <input type="submit" class="btn btn-dark m-2" value="New Blog"/>
        </div>
    </div>
  </div>
</form>
</div>
{% endblock %}

BlogWepsite/main/templates/main/search.html
{% extends 'main/base.html' %}


{% block content %}
<div class="container">
    <h2> Search for blog !</h2>

    <div class="row">
        {% for post in search_blog %}
            <div class="col-3">
                <div class="p-4 shadow" >
                    <a href="{% url 'main:blog_detail' blog.id %}"><h4>{{ blog.title }}</h4></a>
                
                </div>
            </div>
        <h6 class="card-subtitle mb-2 text-muted">
            {% if post.is_pubilshed %} 
                Pubilshed
            {% else %}
                Not Pubilshed
            {% endif %}
            </h6>
            <p class="card-text">Content: {{ blog.content }}</p>
            <p class="card-text">Published: {{ blog.publish_date }}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

BlogWepsite/main/templates/main/update.html
{% extends 'main/base.html' %}

{% block title %} Add a New Blog {% endblock %}

{% block content %}


<div class="container">
<h2>Add a New blog</h2>

<form action="" method="POST">
  <div class="mt-3">
      <label class="form-label">Title</label>
      <input type="text" name="title" class="form-control" value="{{ blog.title }}"/>
  </div>

  <div class="mt-3">
      <label class="form-label">content</label>
      <textarea class="form-control" name="content">{{ post.content }}</textarea>
  </div>


  <select name="is_published" value="{{blog.is_published}}" class="form-select m-2" aria-label="Default select example">
        <option selected >Is it published?</option>
        <option value="True"{% if post.is_published == "True" %} selected {% endif %}>Yes</option>
        <option value="False"{% if post.is_published == "False" %} selected {% endif %}>No</option>
  </select>

  <br/>

  <input type="date" name="publish_date" placeholder="Publish date" class= "m-2" value="Update blog"/>

  <br/>
  <input type="submit" class="btn btn-dark m-2" value="New Blog"/>
</form>

</div>



{% endblock %}